### ISSUE TITLE
Commas after match arms with braces

### ISSUE THREAD

**Issue by fenhl** [madmalik/rustformat#4]
Commas are not needed after match arms with braces, and should always be omitted in this case. Although not explicitly stated, this rule [appears](http://aturon.github.io/style/braces.html#match-arms-get-braces,-except-for-single-line-expressions.) in @aturon's style guide.

For example, as seen in the readme, `rustformat` may produce output like the following:

```rust
match format_file(filename.as_ref()) {
    Err(e) => {
        println!("{:?}", e);
        return;
    },
    Ok(_) => {},
}
```

The output should instead look like this:

```rust
match format_file(filename.as_ref()) {
    Err(e) => {
        println!("{:?}", e);
        return;
    }
    Ok(_) => {}
}
```

**Comment by madmalik** [comment]
You are right. I will implement that tomorrow.

**Comment by madmalik** [comment]
For now, i cant make complex code transformation resp. it breaks on edge cases. 
rustfmt won't add commas anymore when they are not needed, but when optional comas are in the source code pre formatting, they will stay in. 

I will close the issue for now. I know that it's not really fixed, but a satisfying solution will require some reengineering that is out of the scope of this issue.
